name: silab
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  collection: ^1.18.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_boxicons: ^3.1.0
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  mobile_scanner: ^6.0.1
  pinput: ^4.0.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.2
  timeago: ^3.7.0
  timer_count_down: ^2.2.2
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/image/
